# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://pylSER.github.io
date_format: "ordinal"
title: pylSER | MedCare
subtitle: "挽救健忘症救助中心"
description: "Personal Blog of pylSER"
keywords: pylSER, Pei Yulin
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/pylSER/pylSER.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Pei Yulin
organization: Software Institute, NJU
organization_url:
location: NanJing, China
email: 141250099@smail.nju.edu.cn

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: pylSER
douban_username: xxx
facebook_username: Pei Yulin
weibo_username: xxx
zhihu_username: xxx
twitter_username: xxx

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: pylSER
disqus_username: pylSER
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Machine Learing, Javascript, CSS3, HCI, 编译原理]
skill_mobile_app_keywords: [Android]
skill_windows_keywords: [Mac OSX, Ubuntu]
